// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADCPNU0rSObvOma4AdnnVWAd-GrMkdHJg',
    appId: '1:705152425665:web:5d5b9989839c3dc8c67e40',
    messagingSenderId: '705152425665',
    projectId: 'werewolfgamemultiplayer',
    authDomain: 'werewolfgamemultiplayer.firebaseapp.com',
     databaseURL: 'https://werewolfgamemultiplayer-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'werewolfgamemultiplayer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7UaOxitwYYrL9d_m1MUzzmqL7csuz8cY',
    appId: '1:705152425665:android:d75dcd8201dfa0e1c67e40',
    messagingSenderId: '705152425665',
    projectId: 'werewolfgamemultiplayer',
    storageBucket: 'werewolfgamemultiplayer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQrJBRsjdf4AqWoa02kn7HXjWqlwTTUKY',
    appId: '1:705152425665:ios:d9a247d1b80a5c11c67e40',
    messagingSenderId: '705152425665',
    projectId: 'werewolfgamemultiplayer',
    storageBucket: 'werewolfgamemultiplayer.firebasestorage.app',
    iosBundleId: 'com.example.werewolfGameMultiplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQrJBRsjdf4AqWoa02kn7HXjWqlwTTUKY',
    appId: '1:705152425665:ios:d9a247d1b80a5c11c67e40',
    messagingSenderId: '705152425665',
    projectId: 'werewolfgamemultiplayer',
    storageBucket: 'werewolfgamemultiplayer.firebasestorage.app',
    iosBundleId: 'com.example.werewolfGameMultiplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADCPNU0rSObvOma4AdnnVWAd-GrMkdHJg',
    appId: '1:705152425665:web:72433cf5d3bd4f05c67e40',
    messagingSenderId: '705152425665',
    projectId: 'werewolfgamemultiplayer',
    authDomain: 'werewolfgamemultiplayer.firebaseapp.com',
    storageBucket: 'werewolfgamemultiplayer.firebasestorage.app',
  );
}
